railsgirls/config/routes.rb
Railsgirls::Application.routes.draw do
  resources :topics

  resources :categories

  match "ideas/reorder" => "ideas#reorder", :as => "ideas_reorder", :via => :get

  resources :ideas

  root :to => redirect('/ideas')

end

railsgirls/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :ideas
end

railsgirls/app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader	
  attr_accessible :description, :name, :picture, :rating, :category_id
  belongs_to :category
end

railsgirls/app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :name
end

railsgirls/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

railsgirls/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

railsgirls/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include ApplicationHelper

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all #.order('ranking asc')
    @ideas = @ideas.sort_by(&:rating)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  def reorder
    new_order = params[:ideas]
    items = Idea.all
    
    # items = User.current(session).quotes # get all quotes belonging to the User currently logged in
    update_order(new_order, items) # the update is in a separate method, so we can reuse it in other controllers
    render :text => nil # we have to render something, since it's a controller action
    # redirect_to index_path
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
    @categories = Category.all
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

railsgirls/app/helpers/application_helper.rb
module ApplicationHelper

	def update_order(new_order, items_to_update)
	  if items_to_update != nil && new_order != nil && items_to_update.count == new_order.count
	    items_to_update.each do |item|
	      item.rating = new_order.index(item.id.to_s) + 1
	      item.save
	    end
	  end
	end

	def call_fake_method(items)
		logger.debug"*********"
	end
end

railsgirls/app/helpers/categories_helper.rb
module CategoriesHelper
end

railsgirls/app/helpers/ideas_helper.rb
module IdeasHelper
end

railsgirls/app/helpers/topics_helper.rb
module TopicsHelper
end

railsgirls/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsgirls/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

railsgirls/app/views/categories/index.html.erb
<h1>Categories</h1>

<table class='table table-striped'>
  <tr>
    <th>Name</th>
    <th colspan='3'>Actions</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

railsgirls/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

railsgirls/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

railsgirls/app/views/ideas/_form.html.erb
<%= form_for(@idea, :html => { :multipart => true }) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :cols => '60', :rows => '4' %>
  </div>
  <div class="field">
    <%= f.label :picture, "Upload a Picture" %>
    <%= f.file_field :picture %>
  </div>
  <div>
    <%= @idea.name.present? %>
    <% if @idea.name.present? %>
      <%= f.label :category %>
      <%= f.collection_select :category_id, @categories, :id, :name %>  
    <% else %>
      <%= f.label :category %>
      <%= f.collection_select :category_id, @categories, :id, :name %>  
    <% end %>
    
  </div>
  <div class="field">
    <%= f.label :rating, "Rate the Idea" %>
    <%= f.text_field :rating, :size => '2' %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsgirls/app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back to Ideas', ideas_path %>

railsgirls/app/views/ideas/index.html.erb
<h1>All my Great Ideas!</h1>

<%= link_to '+ Create a New Idea', new_idea_path %>

<table width='100%' class="table table-striped ui-widget-content">
  <tbody id="sortable">
  <tr>
    <th>Name</th>
    <th width='25%'>Description</th>
    <th>Picture Path</th>
    <th>Category</th>
    <th>Rating</th>
    <th colspan='3'>Actions</th>
  </tr>


<script type="text/javascript">
  //   $( "#sortable" ).sortable({
  //     placeholder: "ui-state-highlight"
  //   });
  //   $( "#sortable" ).disableSelection();
  // });
$(function() {
    $("#sortable").sortable({placeholder: "ui-state-highlight", items:'.idea', axis:'y', cursor: 'move', update: function(){
        $.get('/ideas/reorder', $(this).sortable('serialize'));
    }});
    // $( "#sortable" ).disableSelection();
  // });
});
</script>

<% i =0 %>
<% @ideas.each do |idea| %>
  <tr class="ui-state-default idea" id='ideas_<%= idea.id %>'>
    <td><%= idea.name %></td>
    <td><%= idea.description %></td>
    <td><%= idea.picture %></td>
    <td><%= idea.category.name %></td>
    <td><%= idea.rating %></td>
    <td><%= link_to 'View', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Delete', idea, method: :delete, data: { confirm: 'Are you sure you want to delete this stellar idea?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>

railsgirls/app/views/ideas/new.html.erb
<h1>Add a New Idea</h1>

<%= render 'form' %>

<%= link_to '<< Back to Ideas', ideas_path %>

railsgirls/app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @idea.name %>
</p>

<p>
  <b>Description:</b>
  <%= @idea.description %>
</p>

<p>
  <b>Picture:</b>
  <%= image_tag(@idea.picture_url, :width => 200) if @idea.picture.present? %>
</p>

<p>
  <b>Category:</b>
  <%= @idea.category.name %>
</p>

<p>
  <b>Rating:</b>
  <%= @idea.rating %>
</p>

<%= link_to 'Edit Idea', edit_idea_path(@idea) %> |
<%= link_to 'Back to Ideas', ideas_path %>

railsgirls/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Railsgirls Idea App</title>
  <%= stylesheet_link_tag  "application", :media => "all" %>  
  <%= stylesheet_link_tag  "bootstrap" %> 
  <link rel='stylesheet' href='/assets/javascripts/jquery-ui-1.10.0.custom/css/ui-lightness/jquery-ui-1.10.0.custom.css'>
  <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
  <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
  <%#= javascript_include_tag "jquery-1.9.1" %>
  <%= javascript_include_tag "jquery.tablednd" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <script>
  // $(function() {
  //   $( "#sortable" ).sortable({
  //     placeholder: "ui-state-highlight"
  //   });
  //   // $( "#sortable" ).disableSelection();
  // });
  </script>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Ideas Newbie App</a>
      <ul class="nav">
        <li><a href="/ideas">Ideas</a></li>
        <li><a href="/categories">Categories</a></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

<footer>
<div class="container">
  Rails Girls 2013
</div>
</footer>
</body>
</html>

railsgirls/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsgirls/app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

railsgirls/app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.name %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

railsgirls/app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

railsgirls/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @topic.name %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>